### ISSUE TITLE
FEAT-tooltips

### ISSUE THREAD

**Issue by Exr0n** [Shabang-Systems/Condution#128] opened 2020-07-28 07:06 UTC
**Is your feature request related to a problem? Please describe.**
Hover tooltips for confusing buttons (flag, globe, repeat). 

**Additional context**
[Discord source CIPHER73#4789](https://discordapp.com/channels/691409213653778444/723796928739016704/737560465516920862)

**Comment by Jemoka** [comment] 2020-07-28 15:56
Humph duplicate of #47, but it never got merged, it seemed. Will investigate, but closing this one now.

**Closed by Jemoka** 2020-07-28 15:56 UTC
Labels: aftercare/docs 📑, desktop 🖥, feature 🚄, flow-ux 🏄‍♂️, interaction ☞, needs-triage 📩, niceties 🌷
